[package]
name = "cdd"
version = "0.2.0"
authors = ["sdfnz <git@sdf.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
